### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Honowski** [stockbsd/twitter-media-dl#1]
I downloaded using pip on Ubuntu, I am receiving FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/.twitter.json'

**Comment by Honowski** [comment]
Apologies, realized the config with API was required to be passed.

**Comment by stockbsd** [comment]
ok. 
you can use consumer key/secret  or  bearer_token .

**Comment by nog642** [comment]
This could be made clearer in the README.
