### ISSUE TITLE
.twitter.json Templete needed

### ISSUE THREAD

**Issue by Yang-Xijie** [stockbsd/twitter-media-dl#5]
I checked https://github.com/stockbsd/twitter-media-dl/issues/1, but I still don't know what to put in `.twitter.json`.

**Comment by Yang-Xijie** [comment]
It seems that you need to be a Twitter developer to get the key and secret... username and password is not the case.
Apply to be a Twitter developer here. https://developer.twitter.com/en/apply-for-access

**Comment by Hitomi98** [comment]
> It seems that you need to be a Twitter developer to get the key and secret... username and password is not the case. Apply to be a Twitter developer here. https://developer.twitter.com/en/apply-for-access

Hi what do I put in .twitter.json? I have a developer account and my key/secret key/bearer token
but I do not know what to put in the file. It is not autocreated for me.
Appreciate any help.
Thanks

**Comment by stockbsd** [comment]
{
  "consumer_key": "",
  "consumer_secret": "",
  "bearer_token": ""
}
